# Generated by Django 4.1.7 on 2023-03-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='skills',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
