# Generated by Django 4.1.7 on 2023-03-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0002_alter_projects_body_alter_projects_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='body',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
