# Generated by Django 4.1.7 on 2023-03-20 09:18

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0003_alter_projects_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=400, null=True),
        ),
    ]
