# Generated by Django 4.1.7 on 2023-03-20 09:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0004_alter_projects_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
