# Generated by Django 4.1.7 on 2023-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0005_alter_projects_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
