# Generated by Django 4.1.7 on 2023-03-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0010_comments_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
