# Generated by Django 4.1.7 on 2023-03-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0011_skills_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='logo',
            field=models.ImageField(blank=True, default='skkillogo.png', null=True, upload_to=''),
        ),
    ]
